#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"


alias \
	nv="nvim"\
	grep="grep --color=auto"\
 	ls="ls -hNF --color=auto --group-directories-first"\
	proj="cd ~/Projects"

#not a good solution but whatever
if [[ "$WSLENV" ]]; then
	alias \
		neo="neovide.exe --wsl" \
		cs="cd /mnt/c/Users/Silvhr/Documents/School/CSCE121/" \
		pic="cd /mnt/c/Users/Silvhr/Pictures/"
else
	...="devour"\
	ff="... firefox; exit"\
	pp="... firefox --private-window;exit"\
        todo="... firefox --new-tab https://todoist.com/app/today; exit"\
	z="... zathura"\
        bottles="... flatpak run com.usebottles.bottles"
fi
