# You can put your preferred keybinds here
# https://wiki.hyprland.org/Configuring/Binds/
bind = Super, C, killactive,

bind=Super+Shift,1,movetoworkspace,1
bind=Super+Shift,2,movetoworkspace,2
bind=Super+Shift,3,movetoworkspace,3
bind=Super+Shift,4,movetoworkspace,4
bind=Super+Shift,5,movetoworkspace,5
bind=Super+Shift,6,movetoworkspace,6
bind=Super+Shift,7,movetoworkspace,7
bind=Super+Shift,8,movetoworkspace,8
bind=Super+Shift,9,movetoworkspace,9
bind=Super+Shift,0,movetoworkspace,10
